files:
   - file: /ff/camaro/gradle/gradle-wrapper.properties
     to: gradle/wrapper/gradle-wrapper.properties
   - file: /ff/camaro/eclipse/gitignore.txt
     to: .gitignore
          
commands: [ camaro, base ]
